In [ ]:
pip uninstall project

In [1]:
pip install project --upgrade

Requirement already up-to-date: project in c:\anac\lib\site-packages (20)
Note: you may need to restart the kernel to use updated packages.


In [103]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
from project import handling_missing_values
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelBinarizer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from project import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score as acc
from sklearn.feature_selection import RFE
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import VarianceThreshold
from project import classification_target
from sklearn.feature_selection import SelectKBest, chi2, f_classif
from sklearn.feature_selection import SelectFromModel

In [121]:
df=pd.read_csv("C:/Users/Cemil Turhan/Downloads/train.csv")

In [116]:
print(ames.head())

   Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD   

In [14]:
ames.SalePrice.describe()

count      1460.000000
mean     180921.195890
std       79442.502883
min       34900.000000
25%      129975.000000
50%      163000.000000
75%      214000.000000
max      755000.000000
Name: SalePrice, dtype: float64

In [122]:
handling_missing_values(df)
target = [0 if price <= 120000 else 1 if price <= 200000 else 2 for price in df.SalePrice]


In [123]:
df.BsmtCond = df.BsmtCond.map({'Ex':5 ,'Gd':4 , 'TA':3 ,'Fa':2 ,'Po':1 , 'NoBsmt':0})
df.BsmtQual = df.BsmtQual.map({'Ex':5 ,'Gd':4 , 'TA':3 ,'Fa':2 ,'Po':1 , 'NoBsmt':0})
df.BsmtExposure = df.BsmtExposure.map({'Gd':4, 'Av':3, 'Mn':2, 'No':1, 'NoBsmt':0})
df.BsmtFinType1 = df.BsmtFinType1.map({'GLQ':6,'ALQ':5,'BLQ':4,'Rec':3,'LwQ':2,'Unf':1,'NoBsmt':0})
df.BsmtFinType2 = df.BsmtFinType2.map({'GLQ':6,'ALQ':5,'BLQ':4,'Rec':3,'LwQ':2,'Unf':1,'NoBsmt':0})
    
df.GarageType = df.GarageType.map({'BuiltIn':6, 'Attchd': 5, '2Types':4 , 'Basment':3 , 'Detchd':2, 'CarPort' :1 , 'NoGarage': 0})
df.GarageCond = df.GarageCond.map({'NoGarage':0, 'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5})
df.GarageQual = df.GarageQual.map({'NoGarage':0, 'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5})
df.GarageFinish = df.GarageFinish.map({'Fin':3, 'RFn':2, 'Unf':1, 'NoGarage':0})
df.PavedDrive = df.PavedDrive.map({'Y':3,'P':2, 'N':1 })
    
df.MSZoning = df.MSZoning.map({'FV':1,'C (all)':2,"RL":3,'RM':4,'RH':5})
df.Street = df.Street.map({'Pave':2,'Grvl':1})
df.Alley = df.Alley.map({'NoAlley':0,'Grvl':1, 'Pave':2})
df.LotShape = df.LotShape.map({'Reg':4, 'IR1':3, 'IR2':2, 'IR3':1})
df.ExterCond = df.ExterCond.map({"Ex":5,'Gd':4,'TA':3,'Fa':2,'Po':1})
df.ExterQual = df.ExterQual.map({"Ex":5,'Gd':4,'TA':3,'Fa':2,'Po':1})
    
df.CentralAir = df.CentralAir.map({'Y':1, 'N':0})
df.HeatingQC = df.HeatingQC.map({"Ex":5,'Gd':4,'TA':3,'Fa':2,'Po':1})
df.FireplaceQu = df.FireplaceQu.map({"Ex":5,'Gd':4,'TA':3,'Fa':2,'Po':1, 'Nofireplace':0})
df.KitchenQual = df.KitchenQual.map({"Ex":5,'Gd':4,'TA':3,'Fa':2,'Po':1})
df.PoolQC = df.PoolQC.map({"Ex":4,'Gd':3,'TA':2,'Fa':1,'NoPool':0})
df.Fence = df.Fence.map({'GdPrv':4 , 'MnPrv':3 , 'GdWo':2 , 'MnWw':1 , 'NoFence':0})
    
df.LandSlope = df.LandSlope.map({'Sev':3,'Mod':2, 'Gtl':1 })
df.Functional = df.Functional.map({'Typ':7,'Min1':6,'Min2':5,'Mod':4,'Maj1':3,'Maj2':2,'Sev':1})
df.SaleCondition = df.SaleCondition.map({'Normal':6,'Abnorml':5,'AdjLand':4,'Alloca':3,'Family':2,'Partial':1})

pd.get_dummies(df, drop_first= True)

Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  Alley  \
0        1          60         3         65.0     8450       2      0   
1        2          20         3         80.0     9600       2      0   
2        3          60         3         68.0    11250       2      0   
3        4          70         3         60.0     9550       2      0   
4        5          60         3         84.0    14260       2      0   
...    ...         ...       ...          ...      ...     ...    ...   
1455  1456          60         3         62.0     7917       2      0   
1456  1457          20         3         85.0    13175       2      0   
1457  1458          70         3         66.0     9042       2      0   
1458  1459          20         3         68.0     9717       2      0   
1459  1460          20         3         75.0     9937       2      0   

      LotShape  LandSlope  OverallQual  ...  MiscFeature_Shed  \
0            4          1            7  ...                 0   
1            4          1            6  ...                 0   
2            3          1            7  ...                 0   
3            3          1            7  ...                 0   
4            3          1            8  ...                 0   
...        ...        ...          ...  ...               ...   
1455         4          1            6  ...                 0   
1456         4          1            6  ...                 0   
1457         4          1            7  ...                 1   
1458         4          1            5  ...                 0   
1459         4          1            5  ...                 0   

      MiscFeature_TenC  SaleType_CWD  SaleType_Con  SaleType_ConLD  \
0                    0             0             0               0   
1                    0             0             0               0   
2                    0             0             0               0   
3                    0             0             0               0   
4                    0             0             0               0   
...                ...           ...           ...             ...   
1455                 0             0             0               0   
1456                 0             0             0               0   
1457                 0             0             0               0   
1458                 0             0             0               0   
1459                 0             0             0               0   

      SaleType_ConLI  SaleType_ConLw  SaleType_New  SaleType_Oth  SaleType_WD  
0                  0               0             0             0            1  
1                  0               0             0             0            1  
2                  0               0             0             0            1  
3                  0               0             0             0            1  
4                  0               0             0             0            1  
...              ...             ...           ...           ...          ...  
1455               0               0             0             0            1  
1456               0               0             0             0            1  
1457               0               0             0             0            1  
1458               0               0             0             0            1  
1459               0               0             0             0            1  

[1459 rows x 191 columns]

In [130]:
df=df.drop("SalePrice", axis=1)

In [131]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

In [132]:
X_train, X_test, y_train, y_test = train_test_split(df, target)

In [133]:
rf = RandomForestClassifier()

In [134]:
scaler = StandardScaler()

In [136]:
scaled_data=scaler.fit_transform(X_train)

ValueError: could not convert string to float: 'Lvl'

In [36]:
print(scaled_data)

[[-0.76204663 -0.222801   -0.05243225 ... -0.0687154  -0.08771809
  -1.59902959]
 [ 1.31225566 -0.222801   -0.05243225 ... -0.0687154  -0.08771809
  -0.48931776]
 [-0.76204663 -0.222801   -0.05243225 ... -0.0687154  -0.08771809
   0.99029801]
 ...
 [-0.76204663 -0.222801   -0.05243225 ... -0.0687154   4.95136791
  -0.48931776]
 [ 1.31225566 -0.222801   -0.05243225 ... -0.0687154  -0.08771809
  -0.8592217 ]
 [ 1.31225566 -0.222801   -0.05243225 ... -0.0687154  -0.08771809
  -0.11941382]]


In [58]:
scaled_data.shape

(1094, 259)

### VarianceThreshold Feature Selection
Eliminates features having low variance below threshold. 

In [54]:
thresholder = VarianceThreshold(threshold=.5)

In [55]:
data_var_th=thresholder.fit_transform(scaled_data)

In [56]:
print(data_var_th)

[[-0.76068626 -0.2233921  -0.06057825 ... -0.07941735 -0.08010964
   0.26106108]
 [-0.76068626 -0.2233921  -0.06057825 ... -0.07941735 -0.08010964
  -0.48463296]
 [-0.76068626 -0.2233921  -0.06057825 ... -0.07941735 -0.08010964
  -0.11178594]
 ...
 [-0.76068626 -0.2233921  -0.06057825 ... -0.07941735 -0.08010964
   2.12529618]
 [-0.76068626 -0.2233921  -0.06057825 ... -0.07941735 -0.08010964
  -0.48463296]
 [ 1.31460243 -0.2233921  -0.06057825 ... -0.07941735 -0.08010964
  -1.23032701]]


In [57]:
 data_var_th.shape 

(1094, 252)

In [59]:
rf.fit(data_var_th, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [60]:
rf.score(data_var_th, y_train)

1.0

In [61]:
rf.fit(scaled_data, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [62]:
rf.score(scaled_data, y_train)

1.0

In [64]:
rf.score(X_train, y_train)

0.30438756855575866

In [65]:
rf.score(X_test, y_test)

0.2602739726027397

### SelectKBest Feature Selection
Select features according to the k highest scores using some metrics. Here I used F score.

In [82]:
select_best=SelectKBest(f_classif, k=50)
select_best_2=SelectKBest(f_classif, k=30)

In [100]:
data_best_fit=select_best.fit(X_train, y_train)

C:\anac\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:114: UserWarning: Features [ 69  70  71  96 105 120 207] are constant.
  UserWarning)
C:\anac\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw


In [101]:
data_best_fit.get_support()

array([False,  True, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [75]:
data_best=select_best.fit_transform(X_train, y_train)

C:\anac\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:114: UserWarning: Features [ 69  70  71  96 105 120 207] are constant.
  UserWarning)
C:\anac\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw


In [78]:
data_best

array([[  0,   0,   1, ..., 888,   0,  25],
       [  0,   0,   0, ..., 420, 140,   0],
       [  0,   0,   0, ..., 440,   0,  32],
       ...,
       [  0,   1,   1, ..., 497, 294, 116],
       [  0,   0,   1, ..., 264,  80,   0],
       [  0,   0,   1, ..., 484,   0,   0]], dtype=int64)

In [80]:
rf.fit(data_best, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [81]:
rf.score(data_best, y_train)

1.0

In [83]:
data_best_2=select_best_2.fit_transform(X_train, y_train)

C:\anac\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:114: UserWarning: Features [ 69  70  71  96 105 120 207] are constant.
  UserWarning)
C:\anac\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw


In [98]:
data_best_2fit=select_best_2.fit(X_train, y_train)

C:\anac\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:114: UserWarning: Features [ 69  70  71  96 105 120 207] are constant.
  UserWarning)
C:\anac\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw


In [99]:
data_best_2fit.get_support() #which ones

array([False,  True, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [85]:
rf.fit(data_best_2, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [86]:
rf.score(data_best_2, y_train)

1.0

### Select from Model Using Random Forest
Selects features based on weights

In [88]:
selector_model = SelectFromModel(estimator=RandomForestClassifier()).fit(X_train, y_train)

In [89]:
selector_model.get_support() #to see which features

array([False,  True, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [93]:
new_X_sfm=selector_model.transform(X_train)

In [95]:
rf.fit(new_X_sfm, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [96]:
rf.score(new_X_sfm, y_train)

1.0