In [24]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.feature_selection import RFE
from sklearn.feature_selection import SelectKBest, chi2, f_classif
from sklearn.feature_selection import SelectFromModel
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

In [2]:
df=pd.read_csv("C:/Users/Cemil Turhan/Desktop/MachineLearning_FinalProject/Numerical_train.csv", index_col=0)

In [3]:
target = [0 if price <= 120000 else 1 if price <= 200000 else 2 for price in df.SalePrice]

In [4]:
df = df.drop(labels = 'SalePrice', axis=1).astype("float64")

In [5]:
X_train, X_test, y_train, y_test = train_test_split(df, target)

### SelectKBest Feature Selection
Select features according to the k highest scores using some metrics. Here I used F score.

In [6]:
select_best=SelectKBest(f_classif, k=50)
select_best_2=SelectKBest(f_classif, k=30)

In [7]:
data_best_fit=select_best.fit(X_train, y_train)

C:\anac\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:114: UserWarning: Features [105 123 127 137 175] are constant.
  UserWarning)
C:\anac\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw


In [8]:
data_best_fit.get_support("True")

array([  1,   2,   6,   8,  10,  11,  12,  13,  15,  16,  17,  18,  19,
        23,  24,  25,  26,  27,  29,  32,  33,  36,  37,  39,  40,  41,
        43,  44,  45,  46,  47,  48,  49,  50,  60,  77,  83,  84,  85,
       116, 142, 157, 160, 161, 162, 163, 164, 165, 176, 186], dtype=int64)

In [10]:
data_best_fit_2=select_best_2.fit(X_train, y_train)

C:\anac\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:114: UserWarning: Features [105 123 127 137 175] are constant.
  UserWarning)
C:\anac\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw


In [11]:
data_best_fit_2.get_support("True")

array([  8,  10,  11,  12,  13,  15,  16,  18,  23,  24,  25,  26,  29,
        32,  36,  37,  39,  40,  41,  43,  44,  45,  46,  47,  84, 142,
       157, 161, 163, 164], dtype=int64)

In [20]:
X_train.columns[data_best_fit.get_support("True")]

Index(['MSZoning', 'LotFrontage', 'LotShape', 'OverallQual', 'YearBuilt',
       'YearRemodAdd', 'MasVnrArea', 'ExterQual', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'TotalBsmtSF',
       'HeatingQC', 'CentralAir', '1stFlrSF', '2ndFlrSF', 'GrLivArea',
       'FullBath', 'HalfBath', 'KitchenQual', 'TotRmsAbvGrd', 'Fireplaces',
       'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageCars', 'GarageArea',
       'GarageQual', 'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'SaleCondition', 'Neighborhood_IDOTRR', 'Neighborhood_NoRidge',
       'Neighborhood_NridgHt', 'Neighborhood_OldTown', 'HouseStyle_2Story',
       'Exterior1st_VinylSd', 'Exterior2nd_VinylSd', 'MasVnrType_BrkFace',
       'MasVnrType_None', 'MasVnrType_Stone', 'Foundation_CBlock',
       'Foundation_PConc', 'Foundation_Slab', 'Electrical_SBrkr',
       'SaleType_New'],
      dtype='object')

In [21]:
X_train.columns[data_best_fit_2.get_support("True")]

Index(['OverallQual', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'ExterQual',
       'BsmtQual', 'BsmtCond', 'BsmtFinType1', 'TotalBsmtSF', 'HeatingQC',
       'CentralAir', '1stFlrSF', 'GrLivArea', 'FullBath', 'KitchenQual',
       'TotRmsAbvGrd', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'Neighborhood_NridgHt', 'Exterior1st_VinylSd', 'Exterior2nd_VinylSd',
       'MasVnrType_None', 'Foundation_CBlock', 'Foundation_PConc'],
      dtype='object')

In [12]:
rf = RandomForestClassifier()

In [18]:
rf.fit(data_best_fit.transform(X_train), y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [19]:
rf.score(data_best_fit.transform(X_train), y_train)  #???

1.0

### RFE
Feature ranking with recursive feature elimination.

In [25]:
model = LogisticRegression()
rfe = RFE(model, 50)
fit = rfe.fit(X_train, y_train)

C:\anac\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\anac\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGIS

In [26]:
fit.get_support("True")

array([  0,   1,   2,   6,   8,   9,  10,  11,  13,  15,  17,  18,  19,
        21,  23,  24,  26,  27,  28,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  45,  48,  49,  50,  51,  52,  53,  54,  56,
        57,  58,  59,  60,  85, 136, 142, 150, 157, 163, 164], dtype=int64)

In [27]:
X_train.columns[fit.get_support("True")]

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotShape', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'ExterQual', 'BsmtQual',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinSF2',
       'TotalBsmtSF', 'HeatingQC', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageArea', 'PavedDrive', 'WoodDeckSF',
       'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea',
       'Fence', 'MiscVal', 'MoSold', 'YrSold', 'SaleCondition',
       'Neighborhood_OldTown', 'Exterior1st_HdBoard', 'Exterior1st_VinylSd',
       'Exterior2nd_HdBoard', 'Exterior2nd_VinylSd', 'Foundation_CBlock',
       'Foundation_PConc'],
      dtype='object')

### Select from Model Using Random Forest
Selects features based on weights

In [28]:
selector_model = SelectFromModel(estimator=RandomForestClassifier()).fit(X_train, y_train)

In [29]:
X_train.columns[selector_model.get_support("True")]

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'ExterQual',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtUnfSF', 'TotalBsmtSF', 'HeatingQC', 'CentralAir', '1stFlrSF',
       '2ndFlrSF', 'GrLivArea', 'BsmtFullBath', 'FullBath', 'BedroomAbvGr',
       'KitchenQual', 'TotRmsAbvGrd', 'Fireplaces', 'FireplaceQu',
       'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea',
       'GarageQual', 'GarageCond', 'WoodDeckSF', 'OpenPorchSF', 'MoSold',
       'YrSold', 'SaleCondition', 'Foundation_PConc'],
      dtype='object')